In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import preprocessing

In [2]:
# reading all label encoded data from fiels:

df_train = pd.read_csv('case study data/labelencoded_train_df.csv',dtype={'fullVisitorId': 'str'},index_col=0)
df_test = pd.read_csv('case study data/labelencoded_test_df.csv',dtype={'fullVisitorId': 'str'},index_col=0)

In [3]:
df_train.head()

,visitNumber,visitId,visitStartTime,date,totals.hits,totals.pageviews,totals.timeOnSite,totals.transactions,totals.transactionRevenue,totals.sessionQualityDim,...,device.deviceCategory,geoNetwork.continent,geoNetwork.subContinent,geoNetwork.country,geoNetwork.region,geoNetwork.metro,geoNetwork.city,geoNetwork.networkDomain,fullVisitorId,channelGrouping
0,1.0,1.470041e+09,1.470041e+09,20160801.0,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,2.49e+18,8
1,1.0,1.470046e+09,1.470046e+09,20160801.0,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,9.29e+17,8
2,1.0,1.470113e+09,1.470113e+09,20160801.0,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,1.62e+18,8
3,1.0,1.470163e+09,1.470163e+09,20160802.0,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,7.21e+18,8
4,1.0,1.470286e+09,1.470286e+09,20160803.0,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,5.09e+18,8

In [4]:
df_test.head()

,channelGrouping,date,fullVisitorId,visitId,visitNumber,visitStartTime,device.browser,device.operatingSystem,device.isMobile,device.deviceCategory,...,totals.pageviews,totals.timeOnSite,totals.sessionQualityDim,totals.transactions,totals.transactionRevenue,trafficSource.campaign,trafficSource.source,trafficSource.medium,trafficSource.keyword,trafficSource.adContent
0,5,20180511.0,7.460955084541987e+18,1.526099e+09,2.0,1.526099e+09,24,0,True,1,...,3.0,973.0,1,0.0,0.0,21,6,5,933,34
1,3,20180511.0,4.60252456180441e+17,1.526064e+09,166.0,1.526064e+09,24,22,False,0,...,3.0,49.0,1,0.0,0.0,21,0,6,2651,34
2,5,20180511.0,3.4618085438796027e+18,1.526067e+09,2.0,1.526067e+09,24,12,False,0,...,3.0,24.0,1,0.0,0.0,21,6,5,933,34
3,3,20180511.0,9.751294777121507e+17,1.526108e+09,4.0,1.526108e+09,24,17,True,1,...,4.0,25.0,1,0.0,0.0,21,0,6,2651,34
4,5,20180511.0,8.38167276806573e+18,1.526060e+09,1.0,1.526060e+09,38,14,True,3,...,4.0,49.0,1,0.0,0.0,21,6,5,933,34

In [29]:
df_train['date'] = df_train['date'].astype('str')
df_train.head()

,visitNumber,visitId,visitStartTime,date,totals.hits,totals.pageviews,totals.timeOnSite,totals.transactions,totals.transactionRevenue,totals.sessionQualityDim,...,device.deviceCategory,geoNetwork.continent,geoNetwork.subContinent,geoNetwork.country,geoNetwork.region,geoNetwork.metro,geoNetwork.city,geoNetwork.networkDomain,fullVisitorId,channelGrouping
0,1.0,1.470041e+09,1.470041e+09,20160801,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,2.49e+18,8
1,1.0,1.470046e+09,1.470046e+09,20160801,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,9.29e+17,8
2,1.0,1.470113e+09,1.470113e+09,20160801,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,1.62e+18,8
3,1.0,1.470163e+09,1.470163e+09,20160802,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,7.21e+18,8
4,1.0,1.470286e+09,1.470286e+09,20160803,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,5.09e+18,8

In [24]:
from datetime import datetime

In [38]:
df_train['date'] = pd.to_datetime(df_train['date'], format='%Y%m%d',errors='coerce')

In [39]:
df_train.head()

,visitNumber,visitId,visitStartTime,date,totals.hits,totals.pageviews,totals.timeOnSite,totals.transactions,totals.transactionRevenue,totals.sessionQualityDim,...,device.deviceCategory,geoNetwork.continent,geoNetwork.subContinent,geoNetwork.country,geoNetwork.region,geoNetwork.metro,geoNetwork.city,geoNetwork.networkDomain,fullVisitorId,channelGrouping
0,1.0,1.470041e+09,1.470041e+09,2016-08-01,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,2.49e+18,8
1,1.0,1.470046e+09,1.470046e+09,2016-08-01,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,9.29e+17,8
2,1.0,1.470113e+09,1.470113e+09,2016-08-01,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,1.62e+18,8
3,1.0,1.470163e+09,1.470163e+09,2016-08-02,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,7.21e+18,8
4,1.0,1.470286e+09,1.470286e+09,2016-08-03,1.0,1.0,0.0,0.0,0.0,0,...,0,2,9,215,374,12,824,26018,5.09e+18,8

In [40]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 898309 entries, 0 to 898308
Data columns (total 28 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   visitNumber                898309 non-null  float64
 1   visitId                    898309 non-null  float64
 2   visitStartTime             898309 non-null  float64
 3   date                       897945 non-null  datetime64[ns]
 4   totals.hits                898309 non-null  float64
 5   totals.pageviews           898309 non-null  float64
 6   totals.timeOnSite          898309 non-null  float64
 7   totals.transactions        898309 non-null  float64
 8   totals.transactionRevenue  898309 non-null  float64
 9   totals.sessionQualityDim   898309 non-null  int64
 10  trafficSource.campaign     898309 non-null  int64
 11  trafficSource.source       898309 non-null  int64
 12  trafficSource.medium       898309 non-null  int64
 13  trafficSource.keyword      898309 non-null  int64
 14  trafficSource.adContent    898309 non-null  int64
 15  device.browser             898309 non-null  int64
 16  device.operatingSystem     898309 non-null  int64
 17  device.isMobile            898309 non-null  bool
 18  device.deviceCategory      898309 non-null  int64
 19  geoNetwork.continent       898309 non-null  int64
 20  geoNetwork.subContinent    898309 non-null  int64
 21  geoNetwork.country         898309 non-null  int64
 22  geoNetwork.region          898309 non-null  int64
 23  geoNetwork.metro           898309 non-null  int64
 24  geoNetwork.city            898309 non-null  int64
 25  geoNetwork.networkDomain   898309 non-null  int64
 26  fullVisitorId              898309 non-null  object
 27  channelGrouping            898309 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(8), int64(17), object(1)
memory usage: 192.8+ MB

In [41]:
df_train.isnull().sum()

visitNumber                    0
visitId                        0
visitStartTime                 0
date                         364
totals.hits                    0
totals.pageviews               0
totals.timeOnSite              0
totals.transactions            0
totals.transactionRevenue      0
totals.sessionQualityDim       0
trafficSource.campaign         0
trafficSource.source           0
trafficSource.medium           0
trafficSource.keyword          0
trafficSource.adContent        0
device.browser                 0
device.operatingSystem         0
device.isMobile                0
device.deviceCategory          0
geoNetwork.continent           0
geoNetwork.subContinent        0
geoNetwork.country             0
geoNetwork.region              0
geoNetwork.metro               0
geoNetwork.city                0
geoNetwork.networkDomain       0
fullVisitorId                  0
channelGrouping                0
dtype: int64